version: 2
jobs:
  build:
    working_directory: ~/chusaku
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: Install Bundler and dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Run tests
          command: |
            bundle exec rake test
