version: 2
jobs:
  build:
    working_directory: ~/chusaku
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: Install Bundler and dependencies
          command: |
            gem install bundler
      - restore_cache:
          keys:
            - dep-
      - run:
          name: Install dependencies
          command: |
            bundle install
      - save_cache:
          key: dep-{{ checksum 'Gemfile.lock' }}
          paths:
            - vendor/bundle
            - ~/.bundle
      - run:
          name: Run tests
          command: |
            bundle exec rake test
